config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "top#index"
    get "login" => "sessions#new", as: :login
    resources :students do
      scope module: :students do
        resources :memos
        resources :homeworks, except: [ :show ]
        resources :grades, except: [ :show ]
        resources :attendances, except: [ :show ]
        resources :contacts, except: [ :show ] 
      end
      collection do
        get "assign_homeworks"
        post "create_homeworks"
        get "canceled"
      end
      member do 
        patch "submit_homework"
        patch "leaving_seat"
        patch "increase_number"
        patch "decrease_number"
        patch "increase_number_absence"
        patch "decrease_number_absence"
        post "taking_seat"
      end
    end
    resources :homeworks, only: [ :index ]
    resources :grades, only: [ :index ]
    resources :attendances, only: [ :index ]
    resource :session, only: [ :create, :destroy ]
    resources :contacts, only: [ :index, :destroy ] do
      delete "destroy_all_by_student/:student_id", to: "contacts#destroy_all_by_student", as: "destroy_all_by_student", on: :collection
    end
    resources :announcements
  end

  namespace :student, path: "" do
    root "top#index"
    get "login" => "sessions#new", as: :login
    resource :session, only: [ :create, :destroy ]
    resources :contacts, only: [ :index, :new, :create, :destroy ]
    resources :announcements, only: [ :index, :show ]
    resources :grade, only: [ :show ]
    resource :total, only: [ :show ]
    resource :account, only: [ :show, :edit, :update ]
    resource :password, only: [ :show, :edit, :update ]
  end  
end

app/models/attendance.rb
# == Schema Information
#
# Table name: attendances
#
#  id               :bigint           not null, primary key
#  student_id       :bigint           not null
#  administrator_id :bigint           not null
#  attended_date    :date             not null
#  in_at            :datetime         not null
#  out_at           :datetime
#  staying_time     :string
#  is_with_no_phone :boolean
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Foreign Keys
#
#  fk_rails_...  (administrator_id => administrators.id)
#  fk_rails_...  (student_id => students.id)
#
class Attendance < ApplicationRecord
  belongs_to :administrator
  belongs_to :student

  before_validation :set_out_at_to_nil_if_same_as_in_at

  validates :administrator_id, presence: true
  validates :student_id,  presence: true
  validates :attended_date, presence: true
  validates :in_at, presence: true

  validate :out_at_should_be_later_than_in_at
  validate :only_one_student_must_present_at_time

  before_save :caliculate_staying_time

  def self.monthly_total_staying_time(student_id, year, month)
    start_date = Date.new(year, month, 1)
    end_date = start_date.end_of_month

    attendances = where(student_id: student_id, attended_date: start_date..end_date)

    total_seconds = attendances.sum do |attendance|
      next 0 unless attendance.in_at.present? && attendance.out_at.present?
      (attendance.out_at - attendance.in_at).to_i
    end

    hours = total_seconds / 3600
    minutes = (total_seconds % 3600) / 60
    "#{hours}時間 #{minutes}分"
  end

 # Attendanceモデルの修正
  def previous_week_homework_submitted?
    previous_week_date = attended_date - 7.days
    homework = student.homeworks.find_by(assigned_date: previous_week_date)

    # 宿題が見つからない場合はnilを返し、見つかった場合はis_submittedの値を返す
    homework ? homework.is_submitted : nil
  end



  private 

  def caliculate_staying_time
    if in_at.present? && out_at.present?
      staying_time_seconds = (out_at - in_at).to_i
      staying_time_hours = staying_time_seconds / 3600
      staying_time_minutes = (staying_time_seconds % 3600) / 60
      self.staying_time = "#{staying_time_hours}時間 #{staying_time_minutes}分"
    end
  end

  def set_out_at_to_nil_if_same_as_in_at
    self.out_at = nil if in_at == out_at
  end

  def out_at_should_be_later_than_in_at
    if out_at && in_at && out_at <= in_at
      errors.add(:out_at, "離席時間は出席時間よりも遅くなければなりません")
    end
  end

  def only_one_student_must_present_at_time
    if student.attendances.exists?(out_at: nil) && new_record?
      errors.add(:base, "同じ生徒に対する出席レコードは一つだけ許可されています。")
    end
  end

end

app/controllers/admin/attendances_controller.rb
class Admin::AttendancesController < Admin::Base
  def index
    @attendances = Attendance.order(attended_date: :desc).includes(:student)
    @attendances = @attendances.page(params[:page])
  end 
  
end

app/controllers/admin/students/attendances_controller.rb
class Admin::Students::AttendancesController < Admin::Students::Base
  def index
    @attendances = @student.attendances.order(attended_date: :desc)
  end

  def new
    @attendance = @student.attendances.new(administrator: current_administrator)
  end

  def edit
    @attendance = @student.attendances.find(params[:id])
  end

  def create
    @attendance = @student.attendances.new(attendances_params)
    
    if @attendance.save
      flash.notice = "出席を記録しました。"
      redirect_to :admin_attendances
    else
      flash.now[:alert] = @attendance.errors.full_messages.join(", ")
      render action: "new", status: :unprocessable_entity
    end

  end

  def update
    @attendance = @student.attendances.find(params[:id])
    @attendance.assign_attributes(attendances_params)

    if @attendance.save
      flash.notice = "修正を完了しました。"
      redirect_to :admin_attendances
    else
      render action: "edit", status: :unprocessable_entity
    end
  end

  def destroy
    attendance = @student.attendances.find(params[:id])
    attendance.destroy!
    flash.notice = "出欠を削除しました。"
    redirect_to :admin_attendances
  end

  private

def attendances_params
  params.require(:attendance).permit(:administrator_id, :student_id, :attended_date, :in_at, :out_at, :is_with_no_phone)
end

end

app/views/admin/attendances/_attendance.html.erb
<tr>
  <td>
    <%= link_to( attendance.student.name, [ :admin, attendance.student, :attendances ]) %>
  </td>
  <td><%= attendance.attended_date %></td>
  <td><%= attendance.in_at.strftime("%H:%M:%S") %></td>
  <td><%= attendance.out_at&.strftime("%H:%M:%S")  %></td>
  <td><%= attendance.staying_time %></td>
  <td>
    <label class="checkbox-label">
    <%= check_box_tag "attendance[is_with_no_phone]", 1, attendance.is_with_no_phone, disabled: true, class: "attendance-checkbox" %>
      <span class="checkmark"></span>
    </label>
  </td>
  <td><%= link_to "修正", edit_admin_student_attendance_path(attendance.student_id, attendance.id) %>　　|　　
      <%= link_to "削除", admin_student_attendance_path(attendance.student_id, attendance.id), data: { turbo_confirm: "本当に削除しますか？", turbo_method: :delete } %>
  </td>
</tr>

app/views/admin/attendances/index.html.erb
<% @title = "出席記録" %>
<h1><%= @title %></h1>

<div class="table-wrapper">
  <div class="links">
    <%= link_to "生徒一覧", :admin_students %>
  </div>

  <%= paginate @attendances %>

  <table class="listing">
    <tr>
      <th>氏名</th>
      <th>日付</th>
      <th>入室時間</th>
      <th>退室時間</th>
      <th>滞在時間</th>
      <th>スマホ預かり</th>
      <th>アクション</th>
    </tr>
    <%= render partial: "attendance", collection: @attendances, as: "attendance" %>

    <% if @attendances.empty? %>
      <tr>
        <%= content_tag(:td, "記録がありません", colspan: 7, style: "text-align: center") %>
      </tr>
    <% end %>

  </table>

  <%= paginate @attendances %>

  <div class="links">
    <%= link_to "生徒一覧", :admin_students %>
  </div>
</div>