config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "top#index"
    get "login" => "sessions#new", as: :login
    resources :students do
      scope module: :students do
        resources :memos
        resources :homeworks, except: [ :show ]
        resources :grades, except: [ :show ]
        resources :attendances, except: [ :show ]
        resources :contacts, except: [ :show ] 
      end
      collection do
        get "assign_homeworks"
        post "create_homeworks"
        get "canceled"
      end
      member do 
        patch "submit_homework"
        patch "leaving_seat"
        patch "increase_number"
        patch "decrease_number"
        patch "increase_number_absence"
        patch "decrease_number_absence"
        post "taking_seat"
      end
    end
    resources :homeworks, only: [ :index ]
    resources :grades, only: [ :index ]
    resources :attendances, only: [ :index ]
    resource :session, only: [ :create, :destroy ]
    resources :contacts, only: [ :index, :destroy ] do
      delete "destroy_all_by_student/:student_id", to: "contacts#destroy_all_by_student", as: "destroy_all_by_student", on: :collection
    end
    resources :announcements
  end

  namespace :student, path: "" do
    root "top#index"
    get "login" => "sessions#new", as: :login
    resource :session, only: [ :create, :destroy ]
    resources :contacts, only: [ :index, :new, :create, :destroy ]
    resources :announcements, only: [ :index, :show ]
    resources :grade, only: [ :show ]
    resource :total, only: [ :show ]
    resource :account, only: [ :show, :edit, :update ]
    resource :password, only: [ :show, :edit, :update ]
  end  
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  has_many :announcement_students, dependent: :destroy
  belongs_to :administrator
  has_many :students, through: :announcement_students

  validates :title, presence: true
  validates :content, presence: true
  validates :start_date, presence: true
  validate :start_date_before_end_date

  scope :active, -> { where("end_date IS NULL OR end_date > ?", Date.today) }

  private

  def start_date_before_end_date
    if end_date.present? && start_date.present? && start_date >= end_date
      errors.add(:start_date, " must be before the end date")
    end
  end
end

app/controllers/admin/students/attendances_controller.rb
class Admin::Students::AttendancesController < Admin::Students::Base
  def index
    @attendances = @student.attendances.order(attended_date: :desc)
  end

  def new
    @attendance = @student.attendances.new(administrator: current_administrator)
  end

  def edit
    @attendance = @student.attendances.find(params[:id])
  end

  def create
    @attendance = @student.attendances.new(attendances_params)
    
    if @attendance.save
      flash.notice = "出席を記録しました。"
      redirect_to :admin_attendances
    else
      flash.now[:alert] = @attendance.errors.full_messages.join(", ")
      render action: "new", status: :unprocessable_entity
    end

  end

  def update
    @attendance = @student.attendances.find(params[:id])
    @attendance.assign_attributes(attendances_params)

    if @attendance.save
      flash.notice = "修正を完了しました。"
      redirect_to :admin_attendances
    else
      render action: "edit", status: :unprocessable_entity
    end
  end

  def destroy
    attendance = @student.attendances.find(params[:id])
    attendance.destroy!
    flash.notice = "出欠を削除しました。"
    redirect_to :admin_attendances
  end

  private

def attendances_params
  params.require(:attendance).permit(:administrator_id, :student_id, :attended_date, :in_at, :out_at, :is_with_no_phone)
end

end

app/controllers/admin/students/base.rb
class Admin::Students::Base < Admin::Base
  before_action :fetch_student

  def fetch_student
    @student = Student.find(params[:student_id])
  end
end

app/controllers/admin/students/contacts_controller.rb
class Admin::Students::ContactsController < Admin::Students::Base
  def index
    @contacts = @student.contacts.order(date: :asc)
    @new_contact = Contact.new
    @contacts.where(read: false).update_all(read: true)
  end

  def create
    @contact = current_administrator.contacts.build(contact_params.merge(date: Time.current, is_from_parents: false, student_id: @student.id))

    if @contact.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to contacts_path, notice: 'メッセージが送信されました。' }
      end
    else
      @contacts = @student.contacts.order(date: :asc)
      @new_contact = Contact.new
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    Contact.find(params[:id]).destroy!
    flash.notice = "削除しました。"
  end

  private

  def contact_params
    params.require(:contact).permit(:message, :administrator_id, :student_id, :date, :is_from_parents)
  end
end

app/controllers/admin/students/grades_controller.rb
class Admin::Students::GradesController < Admin::Students::Base
  def index
      @grades = @student.grades.order(year: :desc)
      @test_results = @grades&.group_by { |result| [result.year, result.test_type] }
  end

  def new
    @grade = @student.grades.new
  end

  def show
    @grade = @student.grades.find(params[:id])
  end

  def edit
    @grade = @student.grades.find(params[:id])
  end

  def create
    @student.grades.new(grades_params)
    
    if @student.save
      flash.notice = "成績を登録しました。"
      redirect_to :admin_grades
    else
      render action: "new", status: :unprocessable_entity
    end

  end

  def update
    @grade = @student.grades.find(params[:id])
    @grade.assign_attributes(grades_params)
    
    if grade.save
      flash.notice = "修正を完了しました。"
      redirect_to :admin_grades
    else
      render action: "edit", status: :unprocessable_entity
    end

  end

  def destroy
    grade = @student.grades.find(params[:id])
    grade.destroy!
    flash.notice = "成績を削除しました。"
    redirect_to :admin_grades
  end

  private def grades_params
    params.require(:grade).permit(
      :student_id, :year, :test_type, :subject_type, :score 
    )
  end
end

app/controllers/admin/students/homeworks_controller.rb
class Admin::Students::HomeworksController < Admin::Students::Base
  def index
    @homeworks = @student.homeworks.order(assigned_date: :desc).includes(:administrator)
  end

  def new
    @homework = @student.homeworks.new(administrator: current_administrator)
  end

  def edit
    @homework = @student.homeworks.find(params[:id])
  end

  def create
    @homework = @student.homeworks.new(homework_params)
    
    if @homework.save
      flash.notice = "宿題を課しました。"
      redirect_to :admin_homeworks
    else
      flash.now[:alert] = @homework.errors.full_messages.join(", ")
      render action: "new", status: :unprocessable_entity
    end
  end

  def update
    @homework = @student.homeworks.find(params[:id])
    @homework.assign_attributes(homework_params)

    if @homework.save
      flash.notice = "修正を完了しました。"
      redirect_to :admin_homeworks
    else
      render action: "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @student.homeworks.find(params[:id]).destroy!
    flash.notice = "宿題を削除しました。"
    redirect_to :admin_homeworks
  end

  private

  def homework_params
    params.require(:homework).permit(:administrator_id, :student_id, :homework_type, :assigned_date, :deadline, :page, :is_submitted)
  end
end

app/controllers/admin/students/memos_controller.rb
class Admin::Students::MemosController < Admin::Students::Base
  def index
    @memos = @student.memos.order(input_date: :desc).includes(:administrator)
  end

  def show
    @memo = @student.memos.find(params[:id])
  end 

  def new 
    @memo = @student.memos.new(administrator: current_administrator)
  end

  def edit
    @memo = @student.memos.find(params[:id])
  end

  def create
    @memo = @student.memos.new(memos_params)
    @memo.input_date = Date.current
    
    if @memo.save
      flash.notice = "メモを登録しました。"
      redirect_to :admin_students
    else
      Rails.logger.error("メモの保存に失敗しました: #{@memo.errors.full_messages}")
      render action: "new", status: :unprocessable_entity
    end
  end

  def update
    @memo = @student.memos.find(params[:id])
    @memo.assign_attributes(memos_params)

    if @memo.save
      flash.notice = "修正を完了しました。"
      redirect_to :admin_students
    else
      render action: "edit", status: :unprocessable_entity
    end
  end

  def destroy
    memo = @student.memos.find(params[:id])
    memo.destroy!
    flash.notice = "メモを削除しました。"
    redirect_to :admin_students
  end

  def memos_params
    params. require(:memo).permit(
      :student_id, :input_date, :content, :administrator_id
    )
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::Base
  def index
    @search_form = Admin::StudentSearchForm.new(search_params)
    @students = @search_form.search(Student.order(birthday: :desc).where(cancellation_date: nil))
    @students = @students.page(params[:page])
  end
 
  def show
    @student = Student.includes(
      :homeworks, 
      :homework_forgets,
      :attendances,
      :absences,
      :memos
    ).find(params[:id])
    @homeworks = @student.homeworks.where(is_submitted: false)
    @homeworks_past = @student.homeworks.group_by(&:assigned_date)
    @homework_forgets_this_year = @student.homework_forgets_in_year(Date.today.year)
    @homeworks_past = @student.homeworks.group_by(&:assigned_date)
    @attendances_and_absences = (
      @student.attendances.map { |attendance| [attendance.attended_date, attendance] } +
      @student.absences.map { |absence| [absence.absent_on, nil] })
      .sort_by { |date, _| date }.reverse
    @memos = @student.memos.group_by(&:input_date)
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(students_params)

    if @student.save
      flash.notice = "生徒情報を登録しました。"
      redirect_to :admin_students
    else
      render action: "new", status: :unprocessable_entity
    end
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(students_params)
      flash.notice = "生徒情報を更新しました。"
      redirect_to :admin_students
    else
      render action: "edit", status: :unprocessable_entity
    end
  end

  def destroy
    Student.find(params[:id]).destroy!
    redirect_to :admin_students, notice: "生徒情報を削除しました。"
  end

  def canceled
    @search_form = Admin::StudentSearchForm.new(search_params)
    @students = @search_form.search(Student.order(birthday: :desc).canceled)
    @students = @students.page(params[:page])
  end

  def leaving_seat
    Student.find(params[:id]).attendances.find_by!(out_at: nil).update!(out_at: Time.current)
    flash.notice = "離席しました。"
    redirect_to :admin_students
  end

  def taking_seat
    student = Student.find(params[:id])
    @attendance = student.attendances.new(
      attended_date: Date.today,
      in_at: Time.current,
      out_at: nil,
      administrator_id: current_administrator.id,
      is_with_no_phone: student.has_deposited_phone? 
      )
    flash.notice = "出席しました。" if @attendance.save
    redirect_to :admin_students
  end

  def increase_number
    student = Student.find(params[:id])

    HomeworkForget.create!(
      student_id: student.id,
      count: 1,
      forgetted_on: Date.today
    )
  
    flash[:notice] = "宿題忘れ回数を増やしました。"
    redirect_to admin_students_path
  end

  def decrease_number
    student = Student.find(params[:id])

    last_forget = student.homework_forgets.order(:forgetted_on).last
    if last_forget.present?
      last_forget.destroy!
      flash[:notice] = "宿題忘れ回数を減らしました。"
    else
      flash[:alert] = "宿題忘れの記録がありません。"
    end

    redirect_to admin_students_path
  end

  def increase_number_absence
    student = Student.find(params[:id])

    Absence.create!(
      student_id: student.id,
      count: 1,
      absent_on: Date.today
    )
  
    flash[:notice] = "欠席を記録しました。"
    redirect_to admin_students_path
  end

  def decrease_number_absence
    student = Student.find(params[:id])

    last_absence = student.absences.order(:absent_on).last
    if last_absence.present?
      last_absence.destroy!
      flash[:notice] = "欠席を取り消しました。"
    else
      flash[:alert] = "欠席の記録がありません。"
    end

    redirect_to admin_students_path
  end

  def submit_homework
    Homework.find(params[:homework_id]).update!(is_submitted: true)
    flash.notice = "提出しました。"
    redirect_to :admin_students
  end

  def assign_homeworks
    @student_ids = params[:student_ids]
    
    if @student_ids.nil? 
      redirect_to :admin_students
    end
  end

  def create_homeworks
    @student_ids = params[:student_ids]
    homework_params = params.require(:homework).permit(:homework_type, :page, :assigned_date, :deadline)
    error_occured = false 
  
    @student_ids.each do |id|
      student = Student.find(id)
      homework = student.homeworks.create(homework_params.merge(administrator_id: current_administrator.id))

      unless homework.save
        error_occured = true
        break
      end
    end
    
    if error_occured
      flash.now[:alert] = "入力に誤りがあります。"
      @homework = Homework.new(homework_params)
      render action: "assign_homeworks", status: :unprocessable_entity
    else
      flash[:notice] = "宿題を課しました。"
      redirect_to admin_students_path
    end
  end
  
  private def students_params
    params.require(:student).permit(
      :name, :name_kana, :email, :password, :birthday, :registration_date, :cancellation_date, :has_deposited_phone
    )
  end
  
  def search_params
    params.fetch(:search, {}).permit(:name, :school_grade, :name_kana)
  end
end

app/controllers/student/accounts_controller.rb
class Student::AccountsController < Student::Base
    def show
        @student = current_student
    end

    def edit
        @student = current_student
    end

    def update
        @student = current_student
        @student.assign_attributes(student_params)
        if @student.save
            flash.notice = "アカウント情報を更新しました。"
            redirect_to :student_account
        else
            render action: "edit"
        end
    end

    private def student_params
        params.require(:student).permit(
            :name, :name_kana, :email, :birthday, :has_deposited_phone
        )
    end
end

app/controllers/student/announcements_controller.rb
class Student::AnnouncementsController < Student::Base
  def index
    student = current_student

    if student.nil?
      redirect_to student_login_path, alert: "ログインしてください。"
      return
    end
    
    today = Date.today

    # 生徒に関連するアナウンスメントと全体公開のアナウンスメントを取得
    @announcements = Announcement.left_joins(:announcement_students)
                                 .where("announcement_students.student_id = ? OR announcement_students.id IS NULL", student.id)
                                 .where("announcements.end_date IS NULL OR announcements.end_date >= ?", today)
                                 .distinct
    @announcements = @announcements.page(params[:page])
  end

  def show
    @announcement = Announcement.find(params[:id])
  end
end

app/controllers/student/base.rb
class Student::Base < ApplicationController
before_action :set_student

  private
  
  def set_student
    @student = current_student
  end

  def current_student
    if session[:student_id]
      @current_student ||=
        Student.find_by(id: session[:student_id])
    end
  end

  helper_method :current_student
end

app/controllers/student/contacts_controller.rb
class Student::ContactsController < Student::Base
  def index
    student = current_student

    if student.nil?
      redirect_to student_login_path, alert: "ログインしてください。"
      return
    end
    
    @contacts = @student.contacts.order(date: :asc)
    @new_contact = Contact.new
    @contacts.where(read: false).update_all(read: true)
  end

def create
  @contact = current_student.contacts.build(contact_params.merge(date: Time.current, is_from_parents: true))
  
  if @contact.save
    respond_to do |format|
      format.turbo_stream 
      format.html { redirect_to contacts_path, notice: 'メッセージが送信されました。' }
    end
  else
    @contacts = Contact.all
    @new_contact = Contact.new
    render :index, status: :unprocessable_entity
  end
end

def destroy
  Contact.find(params[:id])&.destroy!
  flash.notice = "削除しました。"
end

private

  def contact_params
    params.require(:contact).permit(:message, :student_id, :date, :is_from_parents)
  end
end

app/controllers/student/grade_controller.rb
class Student::GradeController < Student::Base
  def show
    @student = current_student
    @grades_by_year = @student.grades.group_by(&:year).sort_by { |year, _| -year }.to_h
  end
end

app/controllers/student/passwords_controller.rb
class Student::PasswordsController < Student::Base
  def show
    redirect_to :edit_staff_password
  end

  def edit
    @change_password_form =
      Student::ChangePasswordForm.new(object: current_student)
  end

  def update
    @change_password_form = Student::ChangePasswordForm.new(student_params)
    @change_password_form.object = current_student
    if @change_password_form.save
      flash.notice = "パスワードを変更しました。"
      redirect_to :student_account
    else
      flash.now.alert = "入力に誤りがあります。"
      render action: "edit", status: :unprocessable_entity
    end
  end

  private def student_params
    params.require(:student_change_password_form).permit(
      :current_password, :new_password, :new_password_confirmation
    )
  end
end

app/controllers/student/top_controller.rb
class Student::TopController < Student::Base
  def index
    @unread_contacts_count = Contact.where(read: false).count
    @unread_contacts_count ||= 0

    if current_student
      render action: "dashboard"
    else
      redirect_to student_login_path, alert: "ログインしてください。"
      return
    end
  end
end

app/views/admin/students/_form.html.erb
<div class="notes">
  <span class="mark">*</span> 印のついた項目は入力必須です。
</div>
<div>
  <%= f.label :name, "氏名", class: "required" %>
  <%= f.text_field :name, required: true %>
</div>
<div>
  <%= f.label :name_kana, "氏名（カナ）", class: "required" %>
  <%= f.text_field :name_kana, required: true %>
</div>
<div>
  <%= f.label :birthday, "誕生日" %>
  <%= f.date_field :birthday %>
</div>
<div>
  <%= f.label :email, "メールアドレス", class: "required" %>
  <%= f.text_field :email, required: true %>
</div>
<% if f.object.new_record? %>
<div>
  <%= f.label :password, "初期パスワード", class: "required" %>
  <%= f.password_field :password, size: 32, required: true %>
</div>
<% end %>
<div>
  <%= f.label :registration_date, "入会日", class: "required" %>
  <%= f.date_field :registration_date, required: true %>
</div>
<div>
  <%= f.label :has_deposited_phone, "スマホ預かり設定" %>
  <div class="radio-group" >
    <div class="radio-item">
      <%= f.radio_button :has_deposited_phone, true, id: "has_deposited_phone_true" %>
      <%= f.label "has_deposited_phone_true", "はい" %>
    </div>
    <div class="radio-item">
      <%= f.radio_button :has_deposited_phone, false, id: "has_deposited_phone_false" %>
      <%= f.label "has_deposited_phone_false", "いいえ" %>
    </div>
  </div>
</div>
<div>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "変更" %>
</div>
<% if @student.persisted? %>
  <div>
    <%= f.label :cancellation_date, "退会日"%>
    <%= f.date_field :cancellation_date %>
  </div>
<% end %>

app/views/admin/students/_search_form.html.erb
<%= form_with model: @search_form, scope: "search", url: :admin_students,
    html: { method: :get, class: "search" } do |f| %>
  <div class="form-group">
    <%= f.label :name, "名前:" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :school_grade, "学年:" %>
    <%= f.select :school_grade, Student::GRADES, { include_blank: "すべて" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name_kana, "フリガナ:" %>
    <%= f.text_field :name_kana, class: "form-control" %>
  </div>

  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>

app/views/admin/students/assign_homeworks.html.erb
<h1>宿題内容</h1>

<div id="generic-form">
  <%= form_with url: create_homeworks_admin_students_path, method: :post, scope: :homework, local: true do |f| %>
    <% @student_ids&.each do |id| %>
      <%= hidden_field_tag "student_ids[]", id %>
    <% end %>

    <div>
      <%= f.label :homework_type, "宿題内容", class: "required" %>
      <%= f.select :homework_type, Homework::HOMEWORK_TYPES, { include_blank: "選択してください" }, { class: "form-select", required: true } %>
    </div>

    <div>
      <%= f.label :page, "ページ" %>
      <%= f.text_area :page, class: "form-textarea" %>
    </div>

    <div>
      <%= f.label :assigned_date, "宿題を課す日" %>
      <%= f.date_field :assigned_date, value: Date.current, class: "form-date-field" %>
    </div>

    <div>
      <%= f.label :deadline, "提出日" %>
      <%= f.date_field :deadline, value: Date.current + 7, class: "form-date-field" %>
    </div>

    <div>
      <%= f.submit "宿題を課す", class: "form-submit" %>
    </div>
  <% end %>
</div>

app/views/admin/students/canceled.html.erb
<div class="table-wrapper">
<h2>退会済生徒一覧</h2>
  <%= paginate @students %> 

  <div class="table-scroll">
    <table class="listing">
      <tr>
        <th>氏名</th>
        <th>フリガナ</th>
        <th>学年</th>
        <th>メモ</th>
        <th>スマホ設定</th>
        <th>成績</th>
        <th>メールアドレス</th>
        <th>入会日</th>
        <th>アクション</th>
      </tr>
      <% @students.each do |student| %>
        <tr>
          <td><%= link_to "#{student.name}", [ :admin, student ] %></td>
          <td><%= student.name_kana %></td>
          <td><%= student.school_grade %></td>
          <td><%= link_to "メモ", [ :admin, student, :memos ] %></td>
          <td><%= student.has_deposited_phone ? "有" : "無" %></td>
          <td><%= link_to "成績", [ :admin, student, :grades ] %></td> 
          <td><%= student.email %></td>
          <td><%= student.registration_date.strftime("%Y/%m/%d") %></td>
          <td class="actions">
            <%= link_to "編集", [ :edit, :admin, student ] %> |
            <%= link_to "削除", [ :admin, student ],
              data: { turbo_confirm: "本当に削除しますか？", turbo_method: :delete } %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <%= paginate @students %>
</div>

app/views/admin/students/edit.html.erb
<% @title = "生徒情報の編集" %>
<h1><%= @title %></h1>

<div id="generic-form">
  <%= form_with model: @student, url: [ :admin, @student ] do |f| %>
    <%= render "form", f: f %>
    <div class="buttons">
      <%= f.submit "変更" %>
      <%= link_to "キャンセル", :admin_students %>
    </div>
  <% end %>
</div>

app/views/admin/students/index.html.erb
<div class="table-wrapper">
  <div class="links">
    <%= link_to "生徒登録", :new_admin_student %>
  </div>

  <%= render "search_form" %>
  
  <%= form_with url: assign_homeworks_admin_students_path, method: :get do |form| %>
    <div>
      <%= form.submit "宿題を課す" %>
    </div>

    <%= paginate @students %> 

    <div class="table-scroll">
      <table class="listing">
        <tr>
          <th>選択</th>
          <th>氏名</th>
          <th>フリガナ</th>
          <th>学年</th>
          <th>メモ</th>
          <th>出席</th>
          <th>欠席</th>
          <th>宿題</th>
          <th>宿題忘れ</th>
          <th>スマホ設定</th>
          <th>成績</th>
          <th>メールアドレス</th>
          <th>入会日</th>
          <th>アクション</th>
        </tr>
        <% @students.each do |student| %>
          <tr>
            <td><%= check_box_tag "student_ids[]", student.id %></td>
            <td><%= link_to "#{student.name}", [ :admin, student ] %></td>
            <td><%= student.name_kana %></td>
            <td><%= student.school_grade %></td>
            <td><%= link_to "メモ", [ :admin, student, :memos ] %></td>
            <td>
              <label>
                <% attendance_checked = student.attendances.where(out_at: nil).exists? %>
                <% if attendance_checked %>
                  <%= link_to "着席中", [:leaving_seat, :admin, student],  data: { "turbo-method": :patch }, class: attendance_checked ? 'link active' : 'link inactive' %>
                <% else %>
                  <%= link_to "着席する", [:taking_seat, :admin, student], data: { "turbo-method": :post }, class: attendance_checked ? 'link active' : 'link inactive' %>
                <% end %>
              </label>        
            </td>
            <td>
              <%= "#{student.absences.count}回" %>
              <%= link_to "+", [:increase_number_absence, :admin, student], class: "btn btn-increase", data: { "turbo-method": :patch} %>
              <%= link_to "-", [:decrease_number_absence, :admin, student], class: "btn btn-decrease", data: { "turbo-method": :patch} %>
            </td>
            <td>
              <% homeworks_checked = student.homeworks.where(is_submitted: false).exists? %>
              <% if homeworks_checked %>
                <%= "！" %>
              <% else %>
                <%= "　" %>
              <% end %>
              <%= link_to "宿題一覧", [ :admin, student, :homeworks ] %> 
            </td>
            <td>
              <%= "#{student.homework_forgets.sum(:count)}回" %>
              <%= link_to "+", [:increase_number, :admin, student], class: "btn btn-increase", data: { "turbo-method": :patch} %>
              <%= link_to "-", [:decrease_number, :admin, student], class: "btn btn-decrease", data: { "turbo-method": :patch} %>
            </td>
            <td><%= student.has_deposited_phone ? "有" : "無" %></td>
            <td><%= link_to "成績", [ :admin, student, :grades ] %></td> 
            <td><%= student.email %></td>
            <td><%= student.registration_date.strftime("%Y/%m/%d") %></td>
            <td class="actions">
              <%= link_to "編集", [ :edit, :admin, student ] %> |
              <%= link_to "削除", [ :admin, student ],
                data: { turbo_confirm: "本当に削除しますか？", turbo_method: :delete } %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>

    <%= paginate @students %>
  <% end %>

  <div class="links">
    <%= link_to "生徒登録", :new_admin_student %>
  </div>
</div>

app/views/admin/students/new.html.erb
<% @title = "生徒登録" %>
<h1><%= @title %></h1>

<div id="generic-form">
  <%= form_with model: @student, url: [ :admin, @student ] do |f| %>
    <%= render "form", f: f %>
    <div class="buttons">
      <%= f.submit "登録" %>
      <%= link_to "キャンセル", :admin_students %>
    </div>
  <% end %>
</div>