config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "top#index"
    get "login" => "sessions#new", as: :login
    resources :students do
      scope module: :students do
        resources :memos
        resources :homeworks, except: [ :show ]
        resources :grades, except: [ :show ]
        resources :attendances, except: [ :show ]
        resources :contacts, except: [ :show ] 
      end
      collection do
        get "assign_homeworks"
        post "create_homeworks"
        get "canceled"
      end
      member do 
        patch "submit_homework"
        patch "leaving_seat"
        patch "increase_number"
        patch "decrease_number"
        patch "increase_number_absence"
        patch "decrease_number_absence"
        post "taking_seat"
      end
    end
    resources :homeworks, only: [ :index ]
    resources :grades, only: [ :index ]
    resources :attendances, only: [ :index ]
    resource :session, only: [ :create, :destroy ]
    resources :contacts, only: [ :index, :destroy ] do
      delete "destroy_all_by_student/:student_id", to: "contacts#destroy_all_by_student", as: "destroy_all_by_student", on: :collection
    end
    resources :announcements
  end

  namespace :student, path: "" do
    root "top#index"
    get "login" => "sessions#new", as: :login
    resource :session, only: [ :create, :destroy ]
    resources :contacts, only: [ :index, :new, :create, :destroy ]
    resources :announcements, only: [ :index, :show ]
    resources :grade, only: [ :show ]
    resource :total, only: [ :show ]
    resource :account, only: [ :show, :edit, :update ]
    resource :password, only: [ :show, :edit, :update ]
  end  
end

app/controllers/admin/top_controller.rb
class Admin::TopController < Admin::Base
  def index
    @unread_contacts_count = Contact.where(read: false).count
    @unread_contacts_count ||= 0
    if current_administrator
      render action: "dashboard"
    else
      render action: "index"
    end
  end
end

app/controllers/customer/top_controller.rb
class Customer::TopController < Customer::Base
  def index
    render action: "index"
  end
end

app/controllers/student/top_controller.rb
class Student::TopController < Student::Base
  def index
    @unread_contacts_count = Contact.where(read: false).count
    @unread_contacts_count ||= 0

    if current_student
      render action: "dashboard"
    else
      redirect_to student_login_path, alert: "ログインしてください。"
      return
    end
  end
end

app/views/admin/top/dashboard.html.erb
<% @title = "ダッシュボード" %>
<h1><%= @title %></h1>

<ul class="menu">
  <li><%= link_to "生徒一覧", :admin_students %></li>
  <li><%= link_to  "生徒登録", :new_admin_student %></li>
  <li><%= link_to "出席管理", :admin_attendances %></li>
  <li><%= link_to "未提出宿題", :admin_homeworks %></li>
  <li><%= link_to "成績管理", :admin_grades %></li>
  <li><%= link_to "問い合わせ確認", :admin_contacts %></li>
  <li><%= link_to "お知らせ管理", :admin_announcements %></li>
  <li><%= link_to "退会済み生徒", canceled_admin_students_path %></li>
</ul>

app/views/admin/top/index.html.erb
<% @title = "管理者トップページ" %>
<h1><%= @title %></h1>