config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "top#index"
    get "login" => "sessions#new", as: :login
    resources :students do
      scope module: :students do
        resources :memos
        resources :homeworks, except: [ :show ]
        resources :grades, except: [ :show ]
        resources :attendances, except: [ :show ]
        resources :contacts, except: [ :show ] 
      end
      collection do
        get "assign_homeworks"
        post "create_homeworks"
        get "canceled"
      end
      member do 
        patch "submit_homework"
        patch "leaving_seat"
        patch "increase_number"
        patch "decrease_number"
        patch "increase_number_absence"
        patch "decrease_number_absence"
        post "taking_seat"
      end
    end
    resources :homeworks, only: [ :index ]
    resources :grades, only: [ :index ]
    resources :attendances, only: [ :index ]
    resource :session, only: [ :create, :destroy ]
    resources :contacts, only: [ :index, :destroy ] do
      delete "destroy_all_by_student/:student_id", to: "contacts#destroy_all_by_student", as: "destroy_all_by_student", on: :collection
    end
    resources :announcements
  end

  namespace :student, path: "" do
    root "top#index"
    get "login" => "sessions#new", as: :login
    resource :session, only: [ :create, :destroy ]
    resources :contacts, only: [ :index, :new, :create, :destroy ]
    resources :announcements, only: [ :index, :show ]
    resources :grade, only: [ :show ]
    resource :total, only: [ :show ]
    resource :account, only: [ :show, :edit, :update ]
    resource :password, only: [ :show, :edit, :update ]
  end  
end

app/models/homework.rb
# == Schema Information
#
# Table name: homeworks
#
#  id               :bigint           not null, primary key
#  student_id       :bigint           not null
#  administrator_id :bigint           not null
#  homework_type    :string           not null
#  page             :string           not null
#  assigned_date    :date             not null
#  deadline         :date
#  is_submitted     :boolean          default(FALSE)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Foreign Keys
#
#  fk_rails_...  (administrator_id => administrators.id)
#  fk_rails_...  (student_id => students.id)
#
class Homework < ApplicationRecord
  belongs_to :administrator
  belongs_to :student

  HOMEWORK_TYPES = %w[ 英語精選 英語ワーク 数学精選 数学ワーク 国語ワーク 社会ワーク 理科ワーク 算数コア 国語コア 算数ワーク 国語ワーク その他].freeze

  validates :administrator_id, presence: true
  validates :student_id, presence: true
  validates :homework_type, presence: true, inclusion: { in: HOMEWORK_TYPES }
  validates :page, presence: true
  validates :assigned_date, presence: true
  validate :deadline_after_assigned_date

  private
  def deadline_after_assigned_date
    if deadline.present? && assigned_date.present? && deadline <= assigned_date
      errors.add(:deadline, "提出日は発表日より後の日付でないといけません。")
    end
  end
end

app/controllers/admin/homeworks_controller.rb
class Admin::HomeworksController < Admin::Base
  def index
    @homeworks = Homework.includes(:student, :administrator).where(is_submitted: false).order(assigned_date: :desc)
    @homeworks = @homeworks.page(params[:page])
  end
end

app/controllers/admin/students/homeworks_controller.rb
class Admin::Students::HomeworksController < Admin::Students::Base
  def index
    @homeworks = @student.homeworks.order(assigned_date: :desc).includes(:administrator)
  end

  def new
    @homework = @student.homeworks.new(administrator: current_administrator)
  end

  def edit
    @homework = @student.homeworks.find(params[:id])
  end

  def create
    @homework = @student.homeworks.new(homework_params)
    
    if @homework.save
      flash.notice = "宿題を課しました。"
      redirect_to :admin_homeworks
    else
      flash.now[:alert] = @homework.errors.full_messages.join(", ")
      render action: "new", status: :unprocessable_entity
    end
  end

  def update
    @homework = @student.homeworks.find(params[:id])
    @homework.assign_attributes(homework_params)

    if @homework.save
      flash.notice = "修正を完了しました。"
      redirect_to :admin_homeworks
    else
      render action: "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @student.homeworks.find(params[:id]).destroy!
    flash.notice = "宿題を削除しました。"
    redirect_to :admin_homeworks
  end

  private

  def homework_params
    params.require(:homework).permit(:administrator_id, :student_id, :homework_type, :assigned_date, :deadline, :page, :is_submitted)
  end
end

app/views/admin/homeworks/_homework.html.erb
<tr>
  <td>
    <%= link_to( homework.student.name, [ :admin, homework.student, :homeworks ]) %>
  </td>
  <td><%= homework.student.school_grade %></td>
  <td><%= homework.homework_type %></td>
  <td><%= homework.page %></td>
  <td><%= homework.assigned_date.strftime("%Y年%m月%d日") %></td>
  <td><%= homework.deadline&.strftime("%Y年%m月%d日") %></td>  
  <td><%= homework.administrator.code %></td>
  <td><%= link_to "修正", edit_admin_student_homework_path(homework.student_id, homework.id) %>　　|　　
  <%= link_to "削除", admin_student_homework_path(homework.student_id, homework.id), data: { turbo_confirm: "本当に削除しますか？", turbo_method: :delete } %>
  </td>
</tr>

app/views/admin/homeworks/index.html.erb
<% @title = "未提出宿題一覧" %>
<h1><%= @title %></h1>

<div class="table-wrapper">
  <div class="links">
    <%= link_to "生徒一覧", :admin_students %>
  </div>

  <%= paginate @homeworks %>

  <table class="listing">
    <tr>
      <th>氏名</th>
      <th>学年</th>
      <th>未提出の宿題</th>
      <th>ページ数</th>
      <th>宿題を課した日</th>
      <th>提出期限</th>
      <th>担当</th>
      <th>アクション</th>
    </tr>
    <%= render partial: "homework", collection: @homeworks, as: "homework" %>

    <% if @homeworks.empty? %>
      <tr>
        <%= content_tag(:td, "現在未提出の宿題はありません", colspan: 8, style: "text-align: center") %>
      </tr>
    <% end %>

  </table>

  <%= paginate @homeworks %>

  <div class="links">
    <%= link_to "生徒一覧", :admin_students %>
  </div>
</div>